### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by ray65536** [mnagel/gnome-keyring-dumper#1]
$ python gnome-keyring-dumper.py 
  File "gnome-keyring-dumper.py", line 15
    print '[%s] %s: %s = %s' % (
                           ^
SyntaxError: invalid syntax

**Comment by mnagel** [comment]
Hi there,

unfortunately it is not enough to fix the syntax change.
The imports

```
import pygtk
import gnomekeyring
```

are also no longer available in Python 3 (as far as I can tell).
The most promising approach right now is to use python-keyring-lib, and I have opened a ticket there asking for some help to get things working: https://bitbucket.org/kang/python-keyring-lib/issue/151/how-is-it-possible-to-list-keyrings-keys

Best Regards
Michael

**Comment by mnagel** [comment]
basic support for python3 is there (in the `-ng` script).
the bash script does not work with python3 yet.

**Comment by ray65536** [comment]
Nice, works. Thank you!
