### ISSUE TITLE
can not import gnomekeyring

### ISSUE THREAD

**Issue by COLABORATI** [mnagel/gnome-keyring-dumper#3]
I am just trying to explore the gnoke keyring features and found your nice tool, however I am having problems with the modules. import gnomekeyring does not find a module, and
`pip install gnomekeyring` 
does not work either. 

what must be pip installed to get this working? Thanks!

**Comment by mnagel** [comment]
what python version do you use and what's your operating system?

**Comment by COLABORATI** [comment]
It's an Ubuntu 14.04 LTS with the default python 2.7.6

**Comment by COLABORATI** [comment]
forget it, everything works now, again I had an encounter with pyenv leading to an unusable python environment. using system python everything is ok.
