### ISSUE TITLE
Does not work with centos7 - no gnomekeyring

### ISSUE THREAD

**Issue by jcwingenbach** [mnagel/gnome-keyring-dumper#4]
When I try to run gnome-keyring-dumper.sh, I receive the following:

ImportError: No module named gnomekeyring

There does not appear to be any rpm that exists in centos 7 matching or containing such.

**Comment by mnagel** [comment]
I don't use Centos and don't know how trustworthy the following source is, but according to https://pkgs.org/download/gnome-python2-gnomekeyring it (`gnome-python2-gnomekeyring`) is included in the Nux Desktop Repository.

**Comment by jcwingenbach** [comment]
Installing the gnome-python2-desktop & gnome-python2-gnomekeyring from that repository enabled the dump to work again (along with a few other rpms from the standard centos7 repo).
